### ISSUE TITLE
Dynamic DNS Not Working

### ISSUE THREAD

**Issue by bashterm** [sandstorm-io/sandcats#156]
I'm behind a DD-WRT router trying to host my sandstorm server on a VM. I was able to configure the machine to get access through LAN, but now I'm on to the part where I get it through to the outside world.

I've forwarded ports 80,443,6080, and 30025 through to my server and changed the host name and wildcard address to my sandcats domain, fogartino.sandcats.io, but it still isn't working.

There is a setting on my router's config page for ddns, but it needs a username and password, both of which I don't have for sandcats.

Any help or or advice would be appreciated.

**Comment by kentonv** [comment]
Hi Aidan,

AFAICT, the ports you mention are not accepting connections. This could mean that the router is not correctly configured to forward the ports to the Sandstorm machine, or it could mean that the Sandstorm machine itself is not accepting connections, e.g. because Sandstorm isn't running.

You don't need to configure your router for "ddns" -- Sandstorm handles the DNS setup automatically. You only need to forward the ports.

If Sandstorm accepts the connections when you connect to the machine directly (not through the router), then it must be the router config that isn't correct, but I don't know what to advise on how to fix it since every router is different.

**Comment by bashterm** [comment]
I have actually solved the problem. I discovered, much to my dissatisfaction, that my ISP has implemented a system known as CGNAT, in which they essentially place my home router behind one of their routers, due to the IPv4 shortage. This is why sandcats could not find my server. Although I had forwarded the ports on my router, the router in front of mine was refusing the connection.

I'm going to have to figure out a solution, but since it clearly isn't on the sandcats side as I thought it was I can find an answer somewhere else.

Thanks for your time!

bashterm
